name: Build and Release Mobile Apps

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  issues: write
  pull-requests: write
  deployments: write
  packages: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Android SDK Tools
        run: |
          echo "y" | sudo softwareupdate --install-rosetta
          echo "ANDROID_HOME=/Users/runner/Library/Android/sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=/Users/runner/Library/Android/sdk" >> $GITHUB_ENV
          echo "/Users/runner/Library/Android/sdk/platform-tools" >> $GITHUB_PATH

          # Download and install command line tools
          wget -q https://dl.google.com/android/repository/commandlinetools-mac-9477386_latest.zip
          unzip -q commandlinetools-mac-9477386_latest.zip
          mkdir -p $ANDROID_HOME/cmdline-tools/
          mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest

          # Accept licenses and install required packages
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.0" \
            "ndk;25.2.9519653" \
            "cmake;3.22.1"

      - name: Setup Android SDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          add-to-path: false

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs

      - name: Check Android build
        run: flutter analyze --no-fatal-warnings

      - name: Build Android APK
        run: flutter build apk --release --split-per-abi

      - name: Build Android App Bundle
        run: flutter build appbundle --release

      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/app/outputs/flutter-apk/app-release-*.apk
            build/app/outputs/bundle/release/app-release.aab
            build/ios/iphoneos/app.ipa
          name: Release ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}

            ## Version Information
            - Release Date: $(date +'%Y-%m-%d')
            - Flutter Version: 3.27.1

            ## Downloads
            - [Android APK (arm64-v8a)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/app-release-arm64-v8a.apk)
            - [Android APK (armeabi-v7a)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/app-release-armeabi-v7a.apk)
            - [Android APK (x86_64)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/app-release-x86_64.apk)
            - [Android App Bundle](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/app-release.aab)
            - [iOS IPA](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/app.ipa)

            ## SHA-256 Checksums
            ```
            $(sha256sum build/app/outputs/flutter-apk/app-release-*.apk build/app/outputs/bundle/release/app-release.aab build/ios/iphoneos/app.ipa)
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Close previous failure issues
        if: success()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: [],
              creator: 'github-actions[bot]'
            });

            for (const issue of issues.data) {
              if (issue.title === 'Mobile build failed') {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed',
                  state_reason: 'completed'
                });
              }
            }

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Mobile build failed',
              body: 'Mobile build workflow failed on commit ${{ github.sha }}'
            })
